Custom dataset mapper
cmu-sei/juneberry pull request #81
Opened 2022-04-18 20:30 UTC by sei-hmoore

**DatasetMapper updates**
We were previously using detectron2's implementation of DatasetMapper that was imported directly through the detectron2 package. This PR updates our import statement for DatasetMapper (juneberry.juneberry.detectron2.data) to reference a custom DatasetMapper class that exists in Cornelius (cornelius.detectron2.dataset_mapper). This will allow us to now add in our own custom dataset mappings into our new DatasetMapper class.

**Updates to trainer.py**
Updated trainer.py setup() to be more modular in its calls to different configuration settings. Setup now calls 4 methods which each setup a different portion of the training configurations (cfg_settings_setup(), model_setup(cfg, args), dataset_mapper_setup(), setup_loss_evaluator())

2022-04-19 10:37 UTC, sei-amellinger commented on juneberry/detectron2/data.py
> +from cornelius.detectron2.dataset_mapper import DatasetMapper
Is this correct?

2022-04-19 10:42 UTC, sei-amellinger commented on juneberry/detectron2/trainer.py
> +# DM22-0044
Who instructed you to use these document markings?

2022-04-19 10:45 UTC, sei-amellinger commented on juneberry/detectron2/trainer.py
> +        self.cfg = cfg
I think from a subalcassing perspective, shouldn't we have these three lines in the out function?

2022-04-19 10:52 UTC, sei-amellinger commented
detetron2.py should also have new copyright.

2022-04-19 13:24 UTC, sei-mchurilla requested changes
Andrews comment on line 52 is run breaking

2022-04-22 19:39 UTC, sei-mchurilla approved these changes
Briefly reviewed code and it seems acceptable.  Tested and the mapper does not break any operational models.

2022-04-26 20:26 UTC, sei-hmoore commented on juneberry/detectron2/data.py
> +from cornelius.detectron2.dataset_mapper import DatasetMapper
Reverted back to detectron2 DataMapper in https://github.com/cmu-sei/juneberry/pull/81/commits/a75354cc6dc8caa6538b3d29c3c3c557ff7a80cb

2022-04-26 20:26 UTC, sei-hmoore commented on juneberry/detectron2/trainer.py
> +# DM22-0044
Fixed in https://github.com/cmu-sei/juneberry/pull/81/commits/a75354cc6dc8caa6538b3d29c3c3c557ff7a80cb

2022-04-26 20:29 UTC, sei-hmoore commented on juneberry/detectron2/trainer.py
> +        self.cfg = cfg
Makes sense, separated out the comments and `self.cfg = cfg` and `cfg.freeze()` in https://github.com/cmu-sei/juneberry/pull/81/commits/a75354cc6dc8caa6538b3d29c3c3c557ff7a80cb

2022-05-09 11:17 UTC, sei-nwinski commented on juneberry/schemas/model_schema.json
> +                "dataset_mapper": { "$ref": "#/definitions/plugin_item" },
You'll also want to document this field in `docs/specs/model_configuration_specification.md`

2022-05-09 11:23 UTC, sei-nwinski commented on juneberry/mappers/utils.py
> +
Is your IDE configured to follow PEP 8 style conventions? We usually stick to that and it's calling for an extra blank line in this location.

2022-05-09 11:38 UTC, sei-nwinski commented on juneberry/detectron2/data.py
> +def create_mapper(cfg, dataset_mapper, transforms, is_train: bool) -> DatasetMapper:
If you add an arg to an existing function, it's a good idea to confirm that all existing usages of the function are also up-to-date (Pycharm: Right-Click on function name -> Find Usages). You addressed mapper lines in the dt2 trainer, but there are also some in the dt2 evaluator. 

Running the system test leads to the following:
```
2022-05-09 11:22:51,911 ERROR create_mapper() missing 1 required positional argument: 'is_train'
Traceback (most recent call last):
  File "/juneberry/juneberry/scripting.py", line 45, in run_main
    main_fn()
  File "/juneberry/bin/jb_evaluate", line 143, in main
    evaluator.perform_evaluation()
  File "/juneberry/juneberry/evaluation/evaluator.py", line 244, in perform_evaluation
    self.evaluate_data()
  File "/juneberry/juneberry/detectron2/evaluator.py", line 186, in evaluate_data
    mapper = dt2_data.create_mapper(self.cfg, self.model_config.evaluation_transforms, False)
TypeError: create_mapper() missing 1 required positional argument: 'is_train'
TaskError - taskid:2
Command error: '['jb_evaluate', 'text_detect/dt2/ut', 'data_sets/text_detect_val.json']' returned 255
```

2022-05-09 11:44 UTC, sei-nwinski commented on juneberry/detectron2/data.py
> +        logger.info("Using custom dataset mapper to override Detectron2 dataset mapper")
Are you familiar with f-strings in Python? They quickly became one of my favorite things and they're really helpful for log messages like this. Consider something along the lines of 
`logger.info(f"Overriding Detectron2 dataset mapper with the following custom dataset mapper: {dataset_mapper}")`

2022-05-09 11:46 UTC, sei-nwinski commented on juneberry/detectron2/data.py
> +    :param dataset_mapper: A string for the custom dataset mapper to use
Is this really a string if it has `.fqcn` and `.kwargs` attributes? What would the result be if you did a `type(dataset_mapper)` at this point in the code?

2022-05-09 11:55 UTC, sei-nwinski commented on juneberry/detectron2/data.py
> +    if dataset_mapper is not None:
This bit confused me. It made ask "What was the point of constructing the mapper in L150 if you were just going to construct it again with a different set of args and return the second one?

Would it make sense to do all the work to build the aug_list and then worry about any data_mapper steps?

2022-05-09 12:07 UTC, sei-nwinski commented
I think I was able to figure out why `juneberry/trainer.py` is showing up in this PR. I believe the permissions on the file changed from 644 -> 755. Was there a reason for that? If not I think if you were to restore the original permissions then the file would disappear from this PR.

2022-05-11 15:40 UTC, sei-hmoore commented on juneberry/mappers/utils.py
> +
File has been removed due to adjustments in implementation.

2022-05-11 15:41 UTC, sei-hmoore commented on juneberry/schemas/model_schema.json
> +                "dataset_mapper": { "$ref": "#/definitions/plugin_item" },
Line has been removed due to adjustments in implementation.

2022-05-11 15:42 UTC, sei-hmoore commented on juneberry/detectron2/data.py
> +def create_mapper(cfg, dataset_mapper, transforms, is_train: bool) -> DatasetMapper:
Reverted back to original expected args with new implementation.

2022-05-11 15:45 UTC, sei-hmoore commented on juneberry/detectron2/data.py
> +    :param dataset_mapper: A string for the custom dataset mapper to use
Removed comment due to changes in implementation but will make note of this for future comments.

2022-05-11 15:46 UTC, sei-hmoore commented on juneberry/detectron2/data.py
> +        logger.info("Using custom dataset mapper to override Detectron2 dataset mapper")
Removed log output due to changes in implementation but will make note of this for future comments.

2022-05-11 15:48 UTC, sei-hmoore commented
> I think I was able to figure out why `juneberry/trainer.py` is showing up in this PR. I believe the permissions on the file changed from 644 -> 755. Was there a reason for that? If not I think if you were to restore the original permissions then the file would disappear from this PR.

Permissions have been changed and `juneberry/trainer.py` is no longer showing any changes

2022-05-11 17:29 UTC, sei-nwinski approved these changes

2022-05-13 13:35 UTC, sei-mchurilla approved these changes
Code functions as indented.

2022-05-16 13:30 UTC, merged